---
driver:
  name: vagrant
  network:

    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero

platforms:
  - name: bento/centos-7.2

suites:
  - name: default
    data_bags_path: "./data_bags"
    run_list:
      - recipe[chef-jenkins::default]
    attributes:
