# encoding: utf-8
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/spec_helper.rb'
    - 'rakefile.rb'
    - '*.gemspec'
    - 'Gemfile'
    - 'example/rakefile.rb'
    - 'example/Gemfile'
    - 'example/**/*'
    - 'spec/**/*'
Style/Encoding:
  Enabled: true

LineLength:
  Max: 400

SignalException:
  EnforcedStyle: only_raise

CaseIndentation:
  IndentWhenRelativeTo: end